name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  node_version: '18.x'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(node_version)'
  displayName: 'Use Node.js $(node_version)'

- script: npm install
  displayName: 'Install dependencies'

- script: npm start &
  displayName: 'Start Node.js App'

# Optional: Run tests if you add them later
# - script: npm test
#   displayName: 'Run tests'

# Publish the whole repo as artifact "drop"
- publish: $(System.DefaultWorkingDirectory)
  artifact: drop
  displayName: 'Publish artifact: drop'
