# azure-pipelines-cd.yml
trigger: none

resources:
  pipelines:
    - pipeline: ci     # identifier used inside this yaml
      source: 'nodejs-ci'   # <-- replace with your CI pipeline name
      trigger:
        branches:
          include:
            - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'MyAzureServiceConnection'  # replace with your service connection name
  appName: '<your-webapp-name>'                  # replace
  resourceGroup: 'rg-nodeapp'                    # replace

stages:
- stage: Deploy
  displayName: 'Deploy to App Service'
  jobs:
  - deployment: DeployWeb
    displayName: 'Deploy Web App'
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
            - download: ci           # downloads the CI pipeline artifacts
              artifact: drop

            # Deploy to Azure Web App (folder or zip)
            - task: AzureWebApp@1
              inputs:
                azureSubscription: '$(azureSubscription)'
                appName: '$(appName)'
                package: '$(Pipeline.Workspace)/ci/drop'  # artifacts are available here
