trigger: none   # Manual or from Release pipeline

pool:
  name: SelfHostedPool   # Use your custom agent pool

variables:
  webAppName: 'nodejs-cicd-demo'   
  azureServiceConnection: 'NodeJS-CI-CD-Connection' 

steps:
  - download: current
    artifact: drop
    displayName: 'Download build artifact'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      appName: '$(webAppName)'
      package: '$(Pipeline.Workspace)/drop/drop.zip'
    displayName: 'Deploy to Azure Web App'
